### ISSUE TITLE
Web App: Stylise diagram

### ISSUE THREAD

**Issue by jamiehannaford** [rackerlabs/architectures#1]
... with better graphic design skills.

**Comment by rose-coste** [comment]
I'll work on redrawing /web-app/diagram.png, probably with Inkscape or some other free open-source drawing tool so anyone on the team can maintain it. I'll use that drawing as the beginning of a visual vocabulary and image inventory for the project. This can prepare us to develop a library of drawings that are consistent enough to be easily compared to each other.

**Comment by jamiehannaford** [comment]
@rose-coste Cool! Christie Quaranto will also be working on this, in terms of a UI perspective, so it's definitely worth syncing up with her too.

**Comment by rose-coste** [comment]
Christie is signed up to help with the core-infrastructure guide, too, so we should end up with plenty of cross-product & cross-project material that tastes the same to readers.

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi
