### ISSUE TITLE
Web app: think of an open-source test application

### ISSUE THREAD

**Issue by jamiehannaford** [rackerlabs/architectures#6]
We need to think of what open-source software to use as the web application. Some ideas include:

   - Web frameworks: Django, RoR, PHP frameworks like Symfony, etc.
   - Blogging: WordPress, Ghost
   - Social: Diaspora, Discourse
   - Other: Reddit

So far I think WordPress and maybe [Ghost](https://ghost.org) are cool ideas, since they're fairly simple and [ubiquitous](http://www.wpbeginner.com/showcase/40-most-notable-big-name-brands-that-are-using-wordpress/). Plus we already have deployment options on the Rackspace platform (but in Chef).

**Comment by wirehead** [comment]
MediaWiki or Huginn would be different enough from WordPress to be an interesting example.

**Comment by rgbkrk** [comment]
In our current portfolio of things we're deploying, there's the [notebook viewer](http://nbviewer.ipython.org). Some folks use it behind a firewall, against their own GitHub Enterprise, etc. It's not very ubiquitous and fairly niche, but it has its place and people ask me to speak about the architecture all the time (granted, it's a pretty simple CoreOS setup).
